name:                morse-tool
version:             0.1.0.0
github:              "mjoldfield/morse-tool"
license:             BSD3
author:              "Martin Oldfield"
maintainer:          "ex-stack@mjoldfield.com"
copyright:           "Copyright: (c) 2019 Martin Oldfield"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mjoldfield/morse-tool#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: src
    dependencies:
    - text
    - containers
    - neat-interpolation
    - split

executables:
  morse-tool:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse-tool
    - optparse-applicative
    - text

tests:
  morse-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse-tool
